### ISSUE TITLE
Add JSON Syntax Validation to Workflow ⚡

### ISSUE THREAD

**Issue by Nishitbaria** [amanjaiman1/Product_3D#444]
### Is your feature request related to a problem? Please describe.

I would like to suggest an enhancement to the existing workflow "JSON check" to include a step that checks whether the JSON syntax is valid or not. This will help ensure that the JSON files in the repository are correctly formatted and avoid potential issues caused by invalid JSON.

**Explanation:**

By incorporating this enhancement into the workflow, you can ensure that the JSON files in the repository are not only checked for syntax errors but also validated against specific criteria, promoting better quality and correctness of the JSON data.

Please consider implementing this enhancement to enhance the functionality of the existing "JSON check" workflow.

### Describe the solution you'd like

This step performs the JSON syntax validation using a tool like `jq` or a custom script. In the example provided, the `jq` command `jq empty < your_file.json` is used, which checks if the JSON file is empty or not. You can modify this step according to your specific JSON validation requirements.

### Describe alternatives you've considered

**Workflow:**
```yaml
name: JSON check

on:
  push:
    paths:
      - "**.json"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
      - name: json-validation
        run: |
          # Add a step here to perform JSON syntax validation
          # You can use a tool like `jq` or a custom script to validate the JSON syntax
          # For example, you can use the following command:
          #   jq empty < your_file.json
```

This workflow, named "JSON check," is designed to perform a syntax check on JSON files in a repository whenever a push event occurs for files with a `.json` extension. It also runs the syntax check when a pull request is created or updated.

Let's break down the workflow:

1. **Event Trigger**: The workflow is triggered by two events:
   - `push`: Occurs when code is pushed to the repository.
   - `pull_request`: Occurs when a pull request is created or updated.

   The workflow will only execute if the push event affects files with a `.json` extension.

2. **Job**: The workflow defines a single job named `test`. A job is a sequence of steps that run on the same runner.

3. **Runner**: The job specifies that it should run on an `ubuntu-latest` runner. This means the job will run on a machine with the latest version of Ubuntu Linux.

4. **Steps**: The job contains two steps:

   a. **Checkout**: The `actions/checkout@v3` action is used to checkout the repository's code onto the runner. This step ensures that the workflow has access to the latest code.

   b. **JSON Syntax Check**: The `limitusus/json-syntax-check@v2` action is used to perform the JSON syntax check. This action likely validates that the JSON files in the repository have correct syntax and are well-formed. The `with` parameter specifies configuration options for the action. In this case, the `pattern` option is set to `"\\.json$"` using regular expression syntax. This pattern indicates that the action should only check files with a `.json` extension.

Overall, this workflow ensures that whenever changes are made to JSON files in the repository, either through a push or a pull request, a syntax check is performed to validate the correctness of the JSON files.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
