### ISSUE TITLE
Implement Changelog Workflow 🚀

### ISSUE THREAD

**Issue by Nishitbaria** [amanjaiman1/Product_3D#541]
**Description:**
 I would like to propose the addition of a new workflow named "Changelog" to automate the generation of a conventional changelog on the `main` branch whenever code changes are pushed. This workflow will use the existing `TriPSs/conventional-changelog-action@v3` action and `actions/create-release@v1` action to handle changelog generation and release creation, respectively.

**Workflow YAML:**
```yaml
name: Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "false"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
```

**Acceptance Criteria:**
- The Changelog workflow should be triggered automatically on every push to the `main` branch.
- The workflow should utilize the `TriPSs/conventional-changelog-action@v3` and `actions/create-release@v1` actions as specified in the workflow YAML.
- When the workflow runs, it should generate a conventional changelog and create a new release on GitHub if there are any changes.
- The release name and tag should be identical and derived from the generated changelog.
- The conventional changelog should be used as the release body.

**Additional Information:**
I am looking forward to having this automated Changelog workflow in place to streamline our development process and improve transparency with clear and concise changelogs for each release. Please review and consider merging this pull request once it's ready. Thank you!
